export const weatherImages = {
    'partly cloudy': require('./partlycloudy.png'),
    'moderate rain': require('./moderaterain.png'),
    'patchy rain possible': require('./patchyrainposible.png'),
    'patchy rain nearby': require('./patchyrainposible.png'),
    'patchy light rain': require('./patchyrainposible.png'),
    'patchy light rain in area with thunder': require('./heavyrain.png'),
    'sunny': require('./sunny.png'),
    'clear': require('./clear.png'),
    'overcast': require('./overcast.png'),
    'cloudy': require('./cloud.png'),
    'light rain': require('./lightrain.png'),
    'moderate rain at times': require('./moderaterain.png'),
    'heavy rain': require('./heavyrain.png'),
    'heavy rain at times': require('./heavyrain.png'),
    'moderate or heavy freezing rain': require('./heavyrain.png'),
    'moderate or heavy rain shower': require('./heavyrain.png'),
    'moderate or heavy rain with thunder': require('./heavyrain.png'),
    'mist': require('./mist.png'),
    'light drizzle': require('./lightdrizzle.png'),
    'thundery outbreaks in nearby': require('./thunderyoutbreaksinnearby.png'),
    'light rain shower': require('./lightrain.png'),
    'fog': require('./mist.png'),

    'other': { uri: 'https://cdn-icons-png.flaticon.com/512/252/252035.png' }
}